services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: online-book-store
    volumes: 
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - online-bookstore-net

  pgadmin: 
    image: dpage/pgadmin4
    restart: always
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=mail@onlinebookstore.com'
      - 'PGADMIN_DEFAULT_PASSWORD=pgadmin_password'
    ports:
      - 80:80
    networks:
      - online-bookstore-net

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./app:${HOME}
    networks:
      - online-bookstore-net

networks:
  online-bookstore-net: