services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres_password
    ports:
      - 5432:5432
    volumes: 
      - ./db:/var/lib/postgresql/data
    networks:
      - online-bookstore-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  pgadmin: 
    image: dpage/pgadmin4
    restart: always
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=mail@onlinebookstore.com'
      - 'PGADMIN_DEFAULT_PASSWORD=pgadmin_password'
    ports:
      - 5050:80

networks:
  online-bookstore-net: